### PR TITLE
Numerous internal implementation updates

### PR DESCRIPTION
**Pull request by Lucretiel**
- Removed extremely broken `io::Read` implementation
    - The existing implementation didn't update the underlying `StaticVec`; it repeatedly yielded the same bytes on every read call.
    - A correct `Read` implementation would require shifting forward the trailing bytes on every read; this would be massively inefficient.
    - To read from a `StaticVec`, use `io::Cursor` or the `Read` implementation on `&[u8]`. This will be significantly more efficient, as it doesn't require doing massive copies of the unread data into the head position. This is consistent with `Vec`, which also requires clients to use `Cursor` to `io::Read` from them: https://stackoverflow.com/a/42241174/864406
- Simplify write_all to use `?` instead of `unwrap`. 
- Refactored many usages of unsafe, with an emphasis on using safe methods, or "safer" unsafe methods instead of direct pointer copies (especially `push_unchecked` and `get_unchecked`)
- Added safety comments to unsafe methods
- Added many internal safety comments
- Added `Deref<Target=[T]>` and `DerefMut<Target=[T]>` implementations, and removed many methods that already exist as slice methods, especially those that don't benefit from static knowledge of `N`
- Removed custom iterators. They're identical to slice::Iter, except that they're incorrect for Zero Size Types
- Removed some methods (`is_not_empty`) for consistency with existing data structures.
- Removed `AsRef<T>`; I really have no idea why you'd want an AsRef for the first element in the struct. Just use first().unwrap()
- Improved `new_from_array` to not require `T: Copy`. It moves all the items into the `StaticVec`, then drops the remaining ones.
- `as_slice` and `as_slice_mut` now use from_parts
- Added `Clone::clone_from`
- Added some more tests

### CODE REVIEW

**Comment by slightlyoutofphase** [comment]
I'm definitely gonna have to look over all this, but as far as the ZST iterator thing at least: 

You can fill up a StaticVec with ZSTs no problem, and if you attempt to iterate over it, the loop will just return immediately no matter what. This is because `next()` checks `if self.start < self.end` as well as `if self.end > self.start`, and doing `<` or `>` comparisons between raw ZST pointers always returns false, so `next()` just returns `None` right away.

**Comment by Lucretiel** [comment]
But that's exactly what you don't want. A collection of 20 `struct{}` elements should still iterate 20 times.

**Comment by slightlyoutofphase** [comment]
I suppose my point is that I'm unsure what the value of doing the complete iteration loop over a collecton of ZST's really is, when there's not many (if any) observable things it could ever accomplish. If that's actually what people expect though I'll definitely account for it, however. 

I'm pretty sure I'm ultimately gonna want to keep the existing library-native iterators though, as part of the reason I haven't just leaned on `slice` for everything from the outset is that none of it is written with const generics in mind, and I'd rather be able to tweak / optimize things based on them as granularly as possible as the feature continues to develop / eventually becomes stable.

**Comment by Lucretiel** [comment]
I mean, here's a trivial example:

```rust
struct ConstDisplay;

impl Display for ConstDisplay {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        f.write_str("const display")
    }
}

let x = StaticVec::<ConstDisplay, 10>::fill_with(|| ConstDisplay)
for (i, d) in x.iter().enumerate() {
    println!("{}: {}", i, d)
}
```

It's contrived, sure, but it demonstrates my point: ZST iteration is often useful when combinated with other iterators, via chain, zip, or enumerate. A more practical example would be an `Fn` implementation that only touches global data, such as a mutex, and doesn't capture any of its environment.

It's also an issue for generics. If you're writing code that iterates over `StaticVec<T, N>`, you'd expect that your code is executed the same number of times, regardless of whether `T` is zero-size.

More generally, this is a very serious divergence from Rust's current ZST slice/array behavior, which currently goes out of its way to correctly iterate over self.len. I'd find it VERY surprising if `vec.iter()` and `vec.as_slice().iter()` do different things.

**Comment by Lucretiel** [comment]
> none of it is written with const generics in mind

I can understand this in some cases, such as for things that require bounds or capacity checking and can benefit from `const N`, but the iterator implementation is literally identical to a slice, because the generic capacity parameter never becomes relevant to the iteration (all that matters is the actual length).

**Comment by slightlyoutofphase** [comment]
I've started to go over your (rapidly increasing in number it seems) changes more in-depthly. Two things I can say right now:

- I disagree that `read` is "massively broken" or even slightly broken. Nowhere is it specified that when you call read on something, the `u8`s read out must no longer exist in said thing. I suppose the specific implementation of read for slices works like that (I think) but I don't think that matters. IMO if `StaticVec` can be read from without being emptied, that's rather more useful than the opposite.

- Your implementation of `Extend` is non-trivially slower than the existing one, and absolutely nosedives the benchmark performance. After thinking about it I'm pretty sure how it is now is something I arrived at after testing and carefully comparing a **ton** of ways of doing it. As far as I can tell it's the general simplicity of the while loop that compares directly against the constant generic `N` parameter that allows the compiler  to optimize it better than it can anything else.

**Comment by Lucretiel** [comment]
> - I disagree that read is "massively broken" or even slightly broken. Nowhere is it specified that when you call read on something, the u8s read out must no longer exist in said thing

There is not a single other type in the entire Rust ecosystem that behaves this way. It isn't necessary for them to be literally erased from the underlying storage, but is IS necessary for the reader to update its state in some way so that the next call to `read` reads out bytes from where the previous one left off. From the `io::Read::read` documentation:

> Pull some bytes from this source into the specified buffer, returning how many bytes were read.

It's a fundamental assumption of `Read` that a series of `read` calls will have the same concatenated output, regardless of how many `read` calls are required to get it all out. As a user of read, I'd have the expectation that the following two examples result in the same data being populated to `buffer`:

```rust
// Version 1
let mut data = staticvec![1, 2, 3, 4, 5, 6];
let mut buffer = [0; 6];
data.read(&mut buffer[..]).unwrap();

// Version 2
let mut data = staticvec![1, 2, 3, 4, 5, 6];
let mut buffer = [0; 6];
data.read(&mut buffer[0..3]).unwrap();
data.read(&mut buffer[3..6]).unwrap();
```

The standard library also has this expectation; for instance, consider `io::Read::read_to_end`, which fills a `Vec<u8>` by calling `read` in a loop until EOF:

https://github.com/rust-lang/rust/blob/618b01f9fa0a6b4e7e2ce5b3409abe104b80c4a8/src/libstd/io/mod.rs#L371-L401

> IMO if StaticVec can be read from without being emptied, that's rather more useful than the opposite.

I agree, and this is the stance that `Vec` takes by requiring the user to use an `io::Cursor` to read from it. I agree that it shouldn't be necessary to delete the data from `StaticVec`, but it is still necessary to advance the state of your `io::Read` object in some way so that subsequent reads show subsequent data.

> - Your implementation of Extend is non-trivially slower than the existing one

Sure, I'm happy to revert.

**Comment by Lucretiel** [comment]
Done. I did leave the `T: 'a + Copy` version to use `iter.copied()`; it doesn't seem to have impacted the benches (which makes sense, since the compiler would have a very easy time inlining it)

**Comment by slightlyoutofphase** [comment]
I just did a bunch of work in the past few hours on the crate, much of which I think directly addresses some of the concerns you had here. Let me know what you think.

Most of the stuff in your PR that didn't already exist in some form in the crate looks good, at the very least, also.

**Comment by slightlyoutofphase** [comment]
Also, by the way, while I did make the "no copy requirement for `new_from_array`" change that several people had asked about (and that you have in your fork), I'm still kinda thinking it's not actually ok to do that, as was my original suspicion, reflected in the original implementation.

For example, with StaticVec 0.4.2, if you write this:

    struct Struct {
      s: &'static str,
    }
    
    impl Drop for Struct {
      #[inline(always)]
      fn drop(&mut self) {
        println!("Dropping Struct with value: {}", self.s);
      }
    }
    
    fn main() {
      let x = [
        Box::new(Struct { s: "A" }),
        Box::new(Struct { s: "B" }),
        Box::new(Struct { s: "C" }),
      ];
      let y = StaticVec::<Box<Struct>, 1>::new_from_array(x);
    }

it will **not** double drop (everything is dropped separately, once each, as the `println` messages will show, so that's good), but it does give a Miri error, which seems questionable to me. So I may ultimately revert it back to the way it was. 

I'm unaware of any existing data structure with functions of that kind that require *neither* `Copy` or `Clone`, also, which further makes me think you just aren't supposed to do it.

**Comment by Lucretiel** [comment]
What's the actual problem with it? When you pass an array by value, you're transferring ownership of the array (and everything in it) to the function you called. It should therefore be fine to move everything in the array out of it and into the `StaticVec`. I'll run the miri version and see if I can figure out how to adjust to make it happy; my guess is that it's the same issue that requires slice.split_at_mut to be implemented with unsafe.

**Comment by Lucretiel** [comment]
If you revert it, you should change it to `new_from_array(&[T; N2)`. If you're just going to copy everything out of the input array, rather than move it, there's no reason to require the whole array to be passed by value.

**Comment by slightlyoutofphase** [comment]
> What's the actual problem with it? When you pass an array by value, you're transferring ownership of the array (and everything in it) to the function you called. It should therefore be fine to move everything in the array out of it and into the `StaticVec`. I'll run the miri version and see if I can figure out how to adjust to make it happy; my guess is that it's the same issue that requires slice.split_at_mut to be implemented with unsafe.

The implementation *seems* like it should be ok, that's definitely true. And it's definitely not out of the question that Miri is just wrong in this case (the "dangling reference" error it gives is one that I think actually said it "might be incorrect" for a long time.)

**Comment by Lucretiel** [comment]
Can I ask why you added `new_from_slice_internal` and `new_from_slice_internal`? There doesn't seem to be any reason for them to be macros, since they don't do any kind of source transformation; they're just function calls. Even if you want to move the logic out of the constructor– though I'd also ask why you'd want to do that– they can be ordinary functions, right?

**Comment by slightlyoutofphase** [comment]
> Can I ask why you added `new_from_slice_internal` and `new_from_slice_internal`? There doesn't seem to be any reason for them to be macros, since they don't do any kind of source transformation; they're just function calls. Even if you want to move the logic out of the constructor– though I'd also ask why you'd want to do that– they can be ordinary functions, right?

Originally, `new_from_array` and `new_from_slice` literally had the same body, and it was used in like four places with the whole thing written out entirely each time.

For `new_from_array`, the new "no copy" version was originally used two ways with the only difference being what the end of `let length =` was (so I had it passed in as a macro expression.) I switched up which functions called `new_from_slice` and `new_from_array` at some point later which meant I didn't need the "length getter" aspect any more, so I removed it, meaning I guess technically `new_from_array` at least doesn't *need* to be a macro.

I could see in the future having a reason to pass custom bits of syntax in to it again though, so I figured I'd leave it that way as it makes `lib.rs` a bit cleaner anyways.

`new_from_slice` as a macro does still actively reduce code duplication however, because it's the same body for `&` and `&mut`.

**Comment by Lucretiel** [comment]
Sure, but I more mean, why a macro specifically, since the code is just a regular function? You can have `new_from_mut` just call `new_from_slice` directly. In fact, it's not clear to me why a `new_from_mut` method is needed in the first place, since you can call `new_from_slice` with an `&mut [T]` and it will automatically coerce to `&[T]`

**Comment by slightlyoutofphase** [comment]
Hmm, I guess that's true. I suppose I kind of forgot about implicit reference type-coercion being (sometimes) a thing. Perhaps I'll switch that up a bit then.

As far as unique stuff from your PR I like though:
- the clone_from impl
- the DropHelper struct in the test file (and the added tests)
- the added `#Safety` comments (which I meant to get around to once I realized there was a specific doc keyword for it but haven't) at least where still relevant with the latest revision
- Most of the extra internal comments, again at least where still relevant.
- The change to the `Debug` impl
- Checking `is_full()` in the `Write` impl

So if you want to update your branch to something roughly containing my latest revision plus that, I'd be happy to merge it. 

And there's always room for further discussion later on once that's done of course, as then I'll have kind of a better overall picture of what to focus on next / e.t.c.

**Comment by Lucretiel** [comment]
That's fine; I'm happy to split into smaller Pull Requests to make specific
discussion easier and less likely to cause merge conflicts

**Comment by slightlyoutofphase** [comment]
Sounds good, I'll keep an eye on the PR for whenever you've updated the branch then.

**Edit:** also, I added a couple more things to the list of "things I like" _just_ after you replied I think.

**Comment by slightlyoutofphase** [comment]
Any news? I know I've kinda been doing a lot of shuffling of files so it might have been tricky to keep up with. I did end up making the `new_from` functions not-macros again, BTW, as I realized as you suggested it really was sort of dumb and also unnecessary in the case of the `&mut` specific one.

Some of the work I've been doing kind of further covers some of the concerns you had I think, but I don't want to add the particularly unique stuff like the drop helper and the `clone_from` impl on my own as I'd basically be taking credit for something that was entirely your idea / that you wrote.

**Comment by Lucretiel** [comment]
Sorry, I wrote a reply here but I guess I forgot to write it. I've been moving for the last 3 days and have been offline, but today I have a lot of time to work on this. I'm gonna split this pull request into a few different ones to make it easier to provide feedback etc.

**Pull request closed without merging**
