### PR TITLE
Remove rustc compiler features to unbreak rustc nightly build

### PR DESCRIPTION
**Pull request by bnjbvr**
- following landing of https://github.com/rust-lang/rust/pull/73858/,
the `const_saturing_int_methods` feature is in a weird nonexisting
state (stabilized in a future Rust version), so remove it from the list
to unblock compilation.
- also remove other const features that have stabilized in the
meanwhile to avoid compiler warnings.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Seems a pinned version of rustc nightly is pinned in CI, should i bump this too?

**Comment by bnjbvr** [comment]
after looking into it a bit, it seems the latest version of rustc nightly compatible with miri determines which nightly is going to be used, so it's depending on external things that might be hard to fix here? Not sure what to do at this point.

**Comment by bnjbvr** [comment]
Now that miri is available in a more recent nightly, the test passes again, yay. @slightlyoutofphase Can you take a look, please? Thanks!

**Comment by slightlyoutofphase** [comment]
I noticed this PR right after I noticed the automated tests were failing and had already fixed the issues myself. Thanks for being on the ball though, and sorry it took me a little bit to get this all taken care of!

**Pull request closed without merging**
