### PR TITLE
Remove custom iterator; replace with `slice::Iter`

### PR DESCRIPTION
**Pull request by Lucretiel**
Replaced the iterators with `slice::Iter` and `slice::IterMut`. My rationale for this change has two main points:

- An iterator over the contents of a `StaticVec` can't benefit from knowledge of `N`, since it internally just tracks `start` and `end`, which are based on the current `length`. It's not clear to me how a `StaticVec` iterator can ever benefit from knowledge of `N` or even need to be aware of it in the first place.
- Because the implementations are basically identical, it makes more sense to defer to `slice::Iter`, which is reliably *very* tightly designed and optimized, since iterating over slices is one of the most common operations in rust.  This includes implementations of [internal optimization trains](https://doc.rust-lang.org/src/core/slice/mod.rs.html#5554-5560) and of [many of the iterator methods](https://doc.rust-lang.org/src/core/slice/mod.rs.html#3049)

### CODE REVIEW

**Comment by Lucretiel** [comment]
Part of a series of pull requests to split #11 into more easily reviewed parts

**Comment by Lucretiel** [comment]
I can't account for the build failure; it seems that `cargo bench` was randomly `SIGKILL`ed

**Comment by slightlyoutofphase** [comment]
Yeah, I was testing some different stuff with `Clone` and I had committed a  `>` that needed to be an `>=`. 

As far as removing the iterators though, I know they seem a bit redundant right now, but they won't be forever. I've got a lot of ideas for methods for them (that don't exist on the Slice iterators) and other various const-y stuff I intend to slowly ease in.

Plus, with the deref impl and the "as slice" methods, StaticVec has direct access to those iterators anyways if anyone wants it.

**Comment by Lucretiel** [comment]
> As far as removing the iterators though, I know they seem a bit redundant right now, but they won't be forever. I've got a lot of ideas for methods for them (that don't exist on the Slice iterators) and other various const-y stuff I intend to slowly ease in.

These would be API breaking changes anyway, right? Since adding consty stuff to the iterators (still unclear on what that looks like) would at the *very* least would require adding `<N>` as a template parameter to the iterator.

**Comment by slightlyoutofphase** [comment]
> These would be API breaking changes anyway, right? Since adding consty stuff to the iterators (still unclear on what that looks like) would at the _very_ least would require adding `<N>` as a template parameter to the iterator.

I don't think the actual generic constraints for the iterators are something anyone needs to specify directly very often at all, so I'm not sure it would be breaking. What I have in mind is moreso based on methods with const generic parameters (and methods that are just `const fn`s, and methods that consist of both if they ever allow it) anyways though.

We can leave this PR open for now if you want as it doesn't really matter either way, but at this point I don't think I'm going to merge it any time soon (and I feel bad in saying that as I really appreciate your contributions so far.)

Bear with me for a while and hopefully you'll see what I'm getting at.

**Comment by slightlyoutofphase** [comment]
I'm gonna close this now, just because even in the event we did end up revisiting the concept at some point it'd make more sense to do it from a new branch regardless.

**Comment by Lucretiel** [comment]
Thanks for your consideration! I totally understand having other plans in the works. I'll keep an eye on the iterators and see where they land

**Pull request closed without merging**
