### PR TITLE
Update feature dependencies for latest nightly (2021-12-04)

### PR DESCRIPTION
**Pull request by RSSchermer**

### CODE REVIEW

**Comment by slightlyoutofphase** [comment]
Thanks a lot. Sorry for the late reply. I've been regrettably unable to tend to this repo to the extent I'd like recently. Hoping that won't be the case soon.

**Comment by RSSchermer** [comment]
No problem, thank you for a very helpful crate!

Any chance you could publish a new patch version? I maintain a crate (`web-glitz`) that depends on `staticvec` and I'd like to publish a new version of that crate for current nightly myself.

**Comment by slightlyoutofphase** [comment]
> Any chance you could publish a new patch version? I maintain a crate (`web-glitz`) that depends on `staticvec` and I'd like to publish a new version of that crate for current nightly myself.

I've been working on additional fixes / changes / etc for the last couple of days, but I'll probably push a version `0.11.0` to crates.io sometime tomorrow.

**Comment by slightlyoutofphase** [comment]
I've pushed 0.11.0 to crates.io now, so you should be able to go ahead and update `web-glitz`.

**Comment by RSSchermer** [comment]
Thank you very much, happy holidays!

**Comment by slightlyoutofphase** [comment]
No problem! You as well.

**Pull request merged**
