### PR TITLE
String based on StaticVec

### LINKED ISSUE #30: Add support for a StaticString based on StaticVec
I will try implementing it, at least helping with the boilerplate (since I've already done that in https://github.com/paulocsanz/arraystring)

### PR DESCRIPTION
**Pull request by paulocsanz**
Fixes #30

This is not ready for merge.

It's a dump. I basically refactored https://github.com/paulocsanz/arraystring to use StaticVec instead of what it originally used. Most doctests won't pass because they are using the import path from arraystring, I will try to fix that later, also some docs may need to be updated since StaticVec implementation may give different assurances.

There is a bunch of unsafe since I originally implemented it by hand, most of it probably can be removed since StaticVec already does that. And some of it may be wrong because of how StaticVec works, but now it's more of a job of grepping for it and fixing instead of adding boilerplate.

### CODE REVIEW

**Comment by slightlyoutofphase** [comment]
Clearly there's some unresolved imports at the very least. I'll definitely take a thorough look at what you're doing here in general sometime tomorrow though, and see if I can determine a good way to integrate it into the crate. Thanks for wanting to get involved! Always awesome to have new contributors.

**Comment by paulocsanz** [comment]
I've fixed the imports problem, now a few doctests aren't passing, I will fix them. The docs will need a thorough look tho.

Also for some reason a bunch of StaticVec doctests aren't passing, but I haven't changed anything.

**Comment by slightlyoutofphase** [comment]
> Also for some reason a bunch of StaticVec doctests aren't passing, but I haven't changed anything.

Don't worry about those, they're not specifically intended to pass (or be "tests" at all honestly.)

Making them "pass" would require adding a `use` line over every single one, which IMO is pointless. They're just intended as one-liner examples for actual people to read to learn how to use the functions, basically. StaticVec's real tests are all done in `test/test.rs`.

**Comment by paulocsanz** [comment]
All tests are passing now, my biggest gripe is that the error module doesn't work like `String`, returning a different type for each issue, we group them all in an enum. I don't know the best way to do it, so I did the way I usually do.

Also I haven't implemented `Drain` support, to have full parity with `std`'s String

Also, the docs need a look, I won't be able to do it tomorrow tho.

**Comment by paulocsanz** [comment]
> Making them "pass" would require adding a `use` line over every single one, which IMO is pointless. They're just intended as one-liner examples for actual people to read to learn how to use the functions, basically. StaticVec's real tests are all done in `test/test.rs`.

Just saying, it's better to put them, just hiding it like I did in the doctests I commited. Because it makes sure the examples are always up to date, that you haven't forgotten to update in case something changes.

**Comment by slightlyoutofphase** [comment]
> Just saying, it's better to put them, just hiding it like I did in the doctests I commited. Because it makes sure the examples are always up to date, that you haven't forgotten to update in case something changes.

Oh yeah, I get that. I actually have `doctest` set to false in the `Cargo.toml`, though, so I'm not even sure why it was giving you errors. Anyways generally speaking I'm not sure that rustdoc currently handles const generic types exactly as it does normal types, which may be why it's pickier there.

Regardless though I'm confident the actual test suite covers everything in linear order, and I don't believe the one-liner examples are likely to get outdated without me noticing somehow, so I'm not too worried.

As far as the actual string implementation: looks very promising! Like I said, will have to take an in-depth look at it tomorrow and give you some feedback based on that I guess. Thanks so much for what you've done so far though, will definitely be a big addition when it's all said and done!

**Comment by paulocsanz** [comment]
Most of the tests I wrote are doctests, so disabling it would disable them all.

This seriously shouldn't be done.

Also I'm very wary of the formatting configuration, just use the default, I get it may not be ideal, but it's what every single other project uses.

**Comment by slightlyoutofphase** [comment]
> Most of the tests I wrote are doctests, so disabling it would disable them all.
> 
> This seriously shouldn't be done.

I mean, like I said, the crate has an existing standalone test suite in the `tests/test.rs` file, with tests for almost every single function declared in alphabetical order. 

Currently it's 1498 lines long, and will likely get longer in the future. I intentionally did it like this from the very beginning, because I knew specifically that I wanted to have an extensive set of tests that would be way too much to embed directly in the actual sources. Also, having a separate test file allows Miri to be run over it on CI.

Secondly, again, all of the existing example snippets that _are_ embedded directly in the source are just meant to be exactly that: simple one-liner examples, not tests (although many of them are just _copied_ from the actual test suite, meaning I know they work.)

>Also I'm very wary of the formatting configuration, just use the default, I get it may not be ideal, but it's what every single other project uses.

I personally don't think that matters honestly.

**Comment by slightlyoutofphase** [comment]
Ok, I just added the necessary `uses` clauses to all of my existing example snippets, and removed `doctest = false` from the cargo.toml. So they all work now. 

I still don't intend for them to be the real tests at all, but it at least means nothing you've written in this PR will be broken and such.

**Comment by paulocsanz** [comment]
Thanks! Yeah I get that it's not meant to be a test, running doctests are more meant to make sure the examples are up do that. Mine are so detailed to thoroughly explain the API to the user.

I actually test the entire API for parity with String, if you want we can add that too: https://github.com/paulocsanz/arraystring/blob/master/tests/string_parity.rs. It's kinda crazy with the type hackery tho.

**Comment by slightlyoutofphase** [comment]
That external test looks like something that would be useful yeah, as then Miri could run on it as well. 

If you can refactor it to use `StaticString`, I'm basically happy to merge this PR as-is, since it's of super high quality and I can always make little changes here and there later on if necessary.

**Comment by paulocsanz** [comment]
I've added the string parity tests and checked the docs, I'm pretty confident it's good to go.

There is only one thing about the current API, it heavily depends on AsRef and other traits like this. Being heavily generic makes it more ergonomic, but it also may increase compilation times.

We may think of removing the trait bounds now (or in future versions) if the compilation times increase more than accepted.

**Comment by slightlyoutofphase** [comment]
I'll definitely play around with this a bunch and maybe rework it a bit before I publish the next `crates.io` version of `StaticVec`, but I'm gonna go ahead and merge it now as it's definitely already far more than I possibly expected anyone to just show up with. 

Thanks so much! This is insane, actually. You literally were just like "hey, here's *everything*"!

**Pull request merged**
